/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "code-block": {
    name: "code-block",
    description: "A component for code block with syntax highlighting.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/shadcn-pro/components/code-block.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/shadcn-pro/components/code-block.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "use-ai": {
    name: "use-ai",
    description: "A hook for ai",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/shadcn-pro/hooks/use-ai.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/shadcn-pro/hooks/use-ai.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "zoomable-image": {
    name: "zoomable-image",
    description: "A component for zoomable image.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/shadcn-pro/components/zoomable-image.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/shadcn-pro/components/zoomable-image.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "modal": {
    name: "modal",
    description: "A component for modal.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/shadcn-pro/components/modal.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/shadcn-pro/components/modal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pro-table": {
    name: "pro-table",
    description: "A component for pro-table.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/shadcn-pro/components/pro-table.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/shadcn-pro/components/pro-table.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "code-block-demo": {
    name: "code-block-demo",
    description: "An example of the code-block",
    type: "registry:example",
    registryDependencies: ["@shadcn-pro/components/code-block"],
    files: [{
      path: "registry/example/code-block-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/code-block-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "use-ai-hook-demo": {
    name: "use-ai-hook-demo",
    description: "An hook for integrating AI capabilities into your app",
    type: "registry:example",
    registryDependencies: ["@shadcn-pro/hook/use-ai"],
    files: [{
      path: "registry/example/use-ai-hook-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/use-ai-hook-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "zoomable-image-demo": {
    name: "zoomable-image-demo",
    description: "Example showing an image that can be zoomed in and out.",
    type: "registry:example",
    registryDependencies: ["@magicui/zoomable-image"],
    files: [{
      path: "registry/example/zoomable-image-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/zoomable-image-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "modal-demo": {
    name: "modal-demo",
    description: "Example showing a modal.",
    type: "registry:example",
    registryDependencies: ["@shadcn-pro/components/modal"],
    files: [{
      path: "registry/example/modal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/modal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pro-table-demo": {
    name: "pro-table-demo",
    description: "Example showing a pro table.",
    type: "registry:example",
    registryDependencies: ["@shadcn-pro/components/pro-table"],
    files: [{
      path: "registry/example/pro-table-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/pro-table-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }